### ISSUE TITLE
Unsubscribe

### ISSUE THREAD

**Issue by irinapizane** [Nitroceliulioze/movie-rental#3]
https://github.com/Nitroceliulioze/movie-rental/blob/85e97c35d9f7f361b4ab75775bae52b98502ad0f/src/app/components/home/home.component.ts#L21

Why unsubscribe is commented out?

**Comment by Nitroceliulioze** [comment]
did you uncommented unsubscribe in all components?

**Comment by Nitroceliulioze** [comment]
only in movie-item component app crashes, so i left this one commented :)
