### ISSUE TITLE
ngFor for menu buttons

### ISSUE THREAD

**Issue by irinapizane** [Nitroceliulioze/movie-rental#4]
https://github.com/Nitroceliulioze/movie-rental/blob/85e97c35d9f7f361b4ab75775bae52b98502ad0f/src/app/components/navbar/navbar.component.html#L3

Try to loop through the buttons, because now one and the same code is repeated in several lines.
I would do something like this in html:
<button *ngFor="let item of navbarItems" mat-icon-button class="navbar-item" [attr.aria-label]="item.ariaLabel" [routerLink]="item.link">
      {{ item.label }}
</button>

And something like this in ts file:
navbarItems = [
    { label: 'Home', link: '/home', ariaLabel: 'Go to Home page' },
    // other item code goes here
  ];

**Comment by Nitroceliulioze** [comment]
I left out the log out button, because this part gave TS error: (click)="item.clickHandler && this[item.clickHandler]()"
