### ISSUE TITLE
Remove "any"

### ISSUE THREAD

**Issue by irinapizane** [Nitroceliulioze/movie-rental#5]
https://github.com/Nitroceliulioze/movie-rental/blob/85e97c35d9f7f361b4ab75775bae52b98502ad0f/src/app/components/profile/profile.component.ts#L19

 'any' type needs to be removed for the email variable. A check needs to be added to ensure that the email exists in the sessionStorage before making the API call.
 You can do it by wrapping the code in if().
 if (email) {
   console.log( // code goes here until ngOnDestroy
 }

**Comment by Nitroceliulioze** [comment]
no any, no errors :)
